#!/bin/bash

echo select first_name, last_name, email from auth_user where email not ilike \'\%smmk12.org\' order by last_name\; |psql -h schoolvotes.crfmfmw2lj5n.us-east-2.rds.amazonaws.com -d schoolvotesdb -U schoolvotesadmin
