#!/bin/bash
CWD=`pwd`
if [ -n "$1" ]
then
	if [ "$1" == "on" ]
	then
		sed -i .bk 's/DEBUG=False/DEBUG=True/' $CWD/surveys/settings.py
		echo "Debugging on."
	else
		sed -i .bk 's/DEBUG=True/DEBUG=False/' $CWD/surveys/settings.py
		echo "Debugging off."
	fi
fi
