#!/bin/sh

GUNICORN=/usr/local/bin/gunicorn
ROOT=/home/ec2-user/schoolvotes
PID=/var/run/gunicorn.pid

APP=main:application

if [ -f $PID ]; then rm $PID; fi

cd $ROOT
exec $GUNICORN -c $ROOT/gunicorn.conf.py --pid=$PID $APP
