# Generated by Django 2.0.7 on 2018-08-04 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(default='logos/None/no-img.jpg', upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Response')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('expiration_date_time', models.DateField(default=datetime.date.today)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Community')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Survey'),
        ),
    ]
