# Generated by Django 2.0.7 on 2018-08-04 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
