# Generated by Django 2.0.7 on 2018-08-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_communityuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuser',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='votes.Community'),
            preserve_default=False,
        ),
    ]
