# Generated by Django 2.0.7 on 2018-08-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_communityuser_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='_rank',
            field=models.IntegerField(default=0),
        ),
    ]
