# Generated by Django 2.0.7 on 2018-08-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_survey__rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='_rank',
        ),
    ]
