# Generated by Django 2.0.7 on 2018-08-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_remove_survey__rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
