# Generated by Django 2.0.7 on 2018-08-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_survey_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='hide',
        ),
    ]
