# Generated by Django 2.0.7 on 2018-08-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
