# Generated by Django 2.0.7 on 2018-08-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_auto_20180808_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(default='votes/static/logos/None/no-img.jpg', upload_to='votes/static/logos/'),
        ),
    ]
