# Generated by Django 2.0.7 on 2018-08-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0013_auto_20180809_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(default='logos/no-img.jpg', upload_to='logos'),
        ),
    ]
