# Generated by Django 2.0.7 on 2018-09-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0014_auto_20180809_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsevote',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
