# Generated by Django 2.0.7 on 2018-09-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0015_responsevote_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('vote_count', models.IntegerField(default=1)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Survey')),
            ],
        ),
    ]
