# Generated by Django 2.0.7 on 2018-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0016_surveyvoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
