# Generated by Django 2.0.7 on 2018-09-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0017_survey_number_of_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='number_of_votes',
            new_name='max_votes',
        ),
    ]
