# Generated by Django 2.0.7 on 2018-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0018_auto_20180923_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='surveyvoter',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
