# Generated by Django 2.0.7 on 2018-09-24 02:02

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0019_auto_20180923_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyvoter',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyvoter',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 2, 2, 58, 351848, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
